// DOM values and external dataset text are inserted through textContent.
const $=id=>document.getElementById(id);
let run,output;
function text(parent,tag,value){const n=document.createElement(tag);n.textContent=value;parent.append(n);return n;}
function button(parent,label,action){const n=text(parent,'button',label);n.type='button';n.disabled=run.finished;n.onclick=()=>dispatch(action);return n;}
function input(parent,label,value,handler,type='text'){const id='field-'+parent.childElementCount;const l=text(parent,'label',label);l.htmlFor=id;const n=document.createElement('input');n.id=id;n.type=type;n.value=value;n.disabled=run.finished;n.oninput=()=>{try{handler(n.value);$('error').textContent='';}catch(e){$('error').textContent=e.message;}};parent.append(n);return n;}
function updateField(action){act(run,action);const complete=$('complete-set');if(action.type==='reps'&&complete)complete.textContent=run.state.inputReps+'회로 세트 완료';$('packet').textContent=JSON.stringify(userPacket(run),null,2);$('steps').textContent='조작 '+run.events.length+' / '+run.scenario.maxSteps;}
function dispatch(action){try{act(run,action);render();$('error').textContent='';}catch(e){$('error').textContent=e.message;}}

function box(parent,kind='card'){const n=document.createElement('div');n.className=kind;parent.append(n);return n;}
function row(parent,label,value){const n=box(parent,'row');text(n,'span',label);if(value!==undefined)text(n,'span',value).className='value';return n;}
function heading(parent,label){return text(parent,'div',label).className='group-title';}
function foot(parent,value){return text(parent,'p',value).className='footer-note';}
function custom(parent,label,fn){const n=text(parent,'button',label);n.type='button';n.disabled=run.finished;n.onclick=fn;return n;}
function toggle(parent,label,on,fn){const r=row(parent,label);const n=custom(r,'',fn);n.className='switch';n.setAttribute('role','switch');n.setAttribute('aria-label',label);n.setAttribute('aria-checked',String(on));return n;}
function notice(message){$('error').textContent=message;}
function recordSegments(parent,s){const n=box(parent,'segment');for(const [label,screen] of [['최고 기록','records-overview'],['운동 일지','journal-calendar'],['친구','friends-ranking']]){const b=button(n,label,{type:'navigate',screen});b.disabled=run.finished||Boolean(s.draft);b.setAttribute('aria-current',String(s.screen===screen));}}
function calendar(parent,s,journal=false){const c=box(parent);if(!journal){const combined=toggle(c,'운동·일상 함께 보기',false,()=>notice('일상 데이터는 이번 실험에서 제외합니다.'));combined.disabled=true;}const controls=box(c,'calendar-controls');const prev=custom(controls,'‹',()=>notice('이번 실험은 2026년 10월만 재현합니다.'));prev.setAttribute('aria-label','이전 달');text(controls,'h3','2026년 10월');const next=custom(controls,'›',()=>notice('이번 실험은 2026년 10월만 재현합니다.'));next.setAttribute('aria-label','다음 달');custom(controls,'오늘',()=>journal?notice('기준 날짜는 2026-10-12입니다.'):dispatch({type:'select-date',date:'2026-10-12'}));const grid=box(c,'calendar');for(const label of ['월','화','수','목','금','토','일'])text(grid,'div',label).className='weekday';for(let k=0;k<35;k++){const day=k-2;const valid=day>=1&&day<=31;const date='2026-10-'+String(day).padStart(2,'0');const b=custom(grid,'',()=>journal?notice('일지는 아래 목록에서 확인하세요.'):dispatch({type:'select-date',date}));b.className='day'+(valid?'':' other');b.disabled=!valid||run.finished;const d=valid?day:day<1?30+day:day-31;const number=text(b,'strong',String(d));number.className='date-number';b.setAttribute('aria-label',valid?date:(day<1?'2026-09-':'2026-11-')+String(d).padStart(2,'0'));b.setAttribute('aria-pressed',String(valid&&s.selectedDate===date));text(b,'small',valid&&s.scheduledPlans[date]?'푸쉬업':'휴식');if(valid&&s.scheduledPlans[date])text(b,'small','3세트 · 10회');if(journal&&s.workouts.some(w=>w.date===date))text(b,'small','일지 있음');}}
const titles={'workout-ready':'월요일 · 상체 운동','workout-active':'월요일 · 상체 운동','workout-rest':'월요일 · 상체 운동','plan-month':'계획','plan-date-detail':'계획','records-overview':'기록','journal-calendar':'기록','journal-entry':'지난 운동 입력','friends-home':'친구','friends-ranking':'기록','settings':'설정'};
function render(){
 const s=run.state,c=$('screen');c.replaceChildren();$('screen-title').textContent=titles[s.screen];$('tabs').replaceChildren();$('banner').replaceChildren();
 // RootView resets a departed tab's navigation, but retains selected date.
 for(const [label,target] of [['실행',s.activeWorkout?(s.restSeconds>0?'workout-rest':'workout-active'):'workout-ready'],['계획','plan-month'],['기록','records-overview'],['친구','friends-home'],['설정','settings']]){const b=button($('tabs'),label,{type:'navigate',screen:target});b.disabled=run.finished||Boolean(s.draft);const group=s.screen.startsWith('workout')?'실행':s.screen.startsWith('plan')?'계획':['records-overview','journal-calendar','journal-entry','friends-ranking'].includes(s.screen)?'기록':s.screen==='settings'?'설정':'친구';b.setAttribute('aria-current',String(label===group));}
 $('workout-mode').disabled=run.finished||Boolean(s.draft);$('daily-mode').disabled=run.finished||Boolean(s.draft);
 if(s.activeWorkout&&s.screen!=='workout-ready'){const b=box($('banner'),'banner');text(b,'strong',s.restSeconds>0?'휴식 '+s.restSeconds+'초':'운동 중 · '+s.activeWorkout.completedSets+' / 3세트');if(s.restSeconds>0)button(b,'휴식 건너뛰기',{type:'tick',seconds:s.restSeconds});}
 switch(s.screen){
 case 'workout-ready':case 'workout-active':case 'workout-rest':{
  const n=box(c);const done=s.activeWorkout?.completedSets??0;text(n,'strong',done+' / 3 세트');const progress=box(n,'progress');const fill=box(progress,'');fill.style.width=(done/3*100)+'%';if(!s.activeWorkout)button(n,'운동 시작',{type:'start'});
  heading(c,'운동');const ex=box(c);text(ex,'h3','푸쉬업 10회');const dots=box(ex,'dots');for(let i=0;i<3;i++)box(dots,'dot'+(i<done?' done':''));if(s.activeWorkout){text(ex,'small',(done+1)+'세트 · 계획 10회');const actual=box(ex,'actual');text(actual,'strong','실제 횟수');const counter=box(actual,'controls');const minus=button(counter,'−',{type:'reps',value:Math.max(0,s.inputReps-1)});minus.setAttribute('aria-label','실제 횟수 1회 줄이기');input(counter,'실제 횟수',s.inputReps,v=>updateField({type:'reps',value:v}),'number');const plus=button(counter,'+',{type:'reps',value:s.inputReps+1});plus.setAttribute('aria-label','실제 횟수 1회 늘리기');if(done)text(ex,'p','완료한 세트: '+s.activeWorkout.actualReps.join(', ')+'회');}
  const actions=box(ex,'complete-row');const undo=custom(actions,'↶',()=>notice('완료 되돌리기는 이 웹 실험 범위 밖입니다.'));undo.setAttribute('aria-label','세트 완료 되돌리기');undo.disabled=true;const complete=button(actions,s.activeWorkout?s.inputReps+'회로 세트 완료':'세트 완료',{type:'complete-set'});complete.id='complete-set';complete.className='complete';complete.disabled=run.finished||!s.activeWorkout||s.screen==='workout-rest';
  if(s.screen==='workout-rest'){button(c,'가상 시간 30초 이동',{type:'tick',seconds:30});}break;}
 case 'plan-month':heading(c,'캘린더');calendar(c,s);break;
 case 'plan-date-detail':{button(c,'‹ 캘린더',{type:'navigate',screen:'plan-month'});text(c,'h3',s.selectedDate);const p=s.scheduledPlans[s.selectedDate];const n=box(c);text(n,'h3',p?p.title:'휴식');if(p){text(n,'p','푸쉬업 10회');text(n,'small','3세트');}break;}
 case 'records-overview':{
  recordSegments(c,s);if(s.draft?.kind==='record'){const n=box(c,'sheet');text(n,'h3','기록 수정');const actions=box(n,'sheet-actions');button(actions,'취소',{type:'cancel'});button(actions,'저장',{type:'save'});input(n,'편집 중 횟수',s.draft.value,v=>updateField({type:'draft',field:'value',value:v}),'number');text(n,'small','푸쉬업 · '+s.records[0].date);break;}
  for(const name of ['푸쉬업','풀업','신디']){const head=box(c,'row');text(head,'strong',name).className='group-title';const plus=custom(head,'+',()=>notice('새 최고기록 추가는 현재 실험 범위 밖입니다.'));plus.className='plus';plus.setAttribute('aria-label',name+' 기록 추가');const n=box(c);text(n,'small','최고 기록');const r=s.records.find(r=>r.name===name);text(n,'h3',r?r.value+'회':'아직 없음');if(r){const chart=box(n,'chart-empty');text(chart,'span','● '+r.date+' · '+r.value+'회');}else text(n,'div','⌁\n기록을 추가하면 변화가 그래프로 보여요').className='chart-empty';const history=custom(n,'전체 기록 보기 ('+(r?1:0)+'개) ›',()=>{if(r){dispatch({type:'edit-record'});}else notice('기록이 없습니다.');});history.className='history';if(r)history.setAttribute('aria-label','푸쉬업 기록 편집');}
  foot(c,'공통 종목 최고 기록 · 합성 수동 기록 18회가 편집 취소 실험을 위해 준비돼 있습니다.');break;}
 case 'journal-calendar':recordSegments(c,s);button(c,'지난 운동 입력',{type:'new-journal'});heading(c,'운동 일지');calendar(c,s,true);for(const w of s.workouts){const n=box(c);text(n,'h3',w.date+' · '+w.title);text(n,'p','푸쉬업 · '+w.actualReps.join(', ')+'회');}break;
 case 'journal-entry':{
  if(s.draft?.kind==='journal'){const n=box(c,'sheet');text(n,'h3','지난 운동 입력');const actions=box(n,'sheet-actions');button(actions,'취소',{type:'cancel'});button(actions,'일지 저장',{type:'save'});input(n,'날짜',s.draft.date,v=>updateField({type:'draft',field:'date',value:v}),'date');input(n,'제목',s.draft.title,v=>updateField({type:'draft',field:'title',value:v}));text(n,'p','푸쉬업');input(n,'세트별 실제 횟수 (쉼표로 구분)',s.draft.reps,v=>updateField({type:'draft',field:'reps',value:v}));}break;}
 case 'friends-home':{
  heading(c,'내 정보');const n=box(c);row(n,'닉네임','가상 사용자');row(n,'내 친구 코드',s.social.ownCode);const a=row(n,'');custom(a,'▢ 복사',()=>notice('합성 친구 코드: '+s.social.ownCode));custom(a,'↥ 공유',()=>notice('외부 공유는 이 실험에서 실행하지 않습니다.'));toggle(n,'기록 자동 공개',s.social.share_records,()=>dispatch({type:'sharing',enabled:!s.social.share_records}));foot(c,s.social.share_records?'공통 종목 최고기록이 친구·그룹원에게 자동으로 보여요. 친구 코드를 알려 주면 친구 요청을 받을 수 있어요.':'공개를 꺼서 내 기록은 다른 사람에게 보이지 않아요. 친구 기록은 계속 볼 수 있어요.');
  heading(c,'친구 0명');const friends=box(c);text(friends,'p','아직 친구가 없어요. 친구 코드를 주고받아 추가해 보세요.').className='muted';for(const r of s.social.requests)row(friends,r.code+' · 합성 친구','요청 보냄');custom(friends,'＋ 친구 코드로 추가',()=>{friendDialog=true;render();});if(friendDialog){const d=box(c,'sheet');text(d,'h3','친구 추가');text(d,'p','친구에게 받은 친구 코드를 입력해 주세요. 상대가 수락하면 서로의 공통 종목 기록이 보여요.');input(d,'친구 코드 8자리',s.friendCode,v=>updateField({type:'friend-code',value:v}));custom(d,'취소',()=>{friendDialog=false;render();});custom(d,'요청 보내기',()=>{try{act(run,{type:'request'});friendDialog=false;render();$('error').textContent='';}catch(e){notice(e.message);}});}
  heading(c,'그룹');const groups=box(c);custom(groups,'♧ 그룹 만들기',()=>notice('그룹 생성은 이번 실험 범위 밖입니다.'));foot(c,'그룹원은 내 친구 중에서 초대할 수 있어요. 같은 그룹이면 서로 친구가 아니어도 그룹 순위에서 기록이 보여요.');button(c,'새로고침',{type:'refresh'});foot(c,'순위는 기록 탭 → 친구에서 볼 수 있어요');break;}
 case 'friends-ranking':recordSegments(c,s);heading(c,'공통 종목 순위');const rank=box(c);text(rank,'p',s.social.published.length?'가상 사용자 · 푸쉬업 18회':'공개 기록 없음');break;
 case 'settings':{
  heading(c,'저장 상태');const n=box(c);row(n,'☁ 로컬 합성 저장소','기기 메모리');heading(c,'휴식 타이머');const t=box(c);row(t,'세트 사이 휴식: 1분','−　｜　+');row(t,'−/+ 버튼 간격: 15초','−　｜　+');const restToggle=toggle(t,'휴식 끝 알림 소리',false,()=>{});restToggle.disabled=true;foot(c,'이 화면의 설정은 레이아웃 참고용입니다. 실제 기기 설정·동기화·알림은 연결하지 않습니다.');heading(c,'일상 알림');const d=box(c);for(const name of ['일상 알림','알림 소리','아침 요약','저녁 확인']){const settingToggle=toggle(d,name,false,()=>{});settingToggle.disabled=true;}break;}
 }
 if(s.message)foot(c,s.message);$('steps').textContent='조작 '+run.events.length+' / '+run.scenario.maxSteps+' · 기준 시각 '+s.clock;
 $('packet').textContent=JSON.stringify(userPacket(run),null,2);$('finish').disabled=run.finished;
}
let friendDialog=false;
$('daily-mode').onclick=()=>notice('일상 화면은 제공된 사진/시나리오 범위에 없어 이번 실험에서 제외합니다.');
$('workout-mode').onclick=()=>dispatch({type:'navigate',screen:run.state.activeWorkout?(run.state.restSeconds>0?'workout-rest':'workout-active'):'workout-ready'});
function start(){friendDialog=false;run=createRun(PANEL.personas.find(p=>p.id===$('persona').value),PANEL.scenarios.find(s=>s.id===$('scenario').value));output=null;$('review').hidden=true;$('download').disabled=true;$('note').value='';$('error').textContent='';$('context').replaceChildren();text($('context'),'p',run.persona.context);text($('context'),'small',run.persona.goals.join(' · '));$('goal').textContent=run.scenario.userGoal;render();}
for(const [id,items] of [['persona',PANEL.personas],['scenario',PANEL.scenarios]])for(const item of items){const o=document.createElement('option');o.value=item.id;o.textContent=item.name??item.title;$(id).append(o);}
$('persona').value='first-time-recorder';$('scenario').value='start-and-record-set';
$('begin').onclick=start;
$('finish').onclick=()=>{output=finish(run);render();$('review').hidden=false;$('download').disabled=false;$('checks').replaceChildren();for(const c of output.checks)text($('checks'),'div',c.id+' · 웹 '+c.prototypeResult+' / iOS '+c.nativeResult).className='check';$('evidence').textContent=JSON.stringify({events:output.events,before:output.before,after:output.after},null,2);};
$('download').onclick=()=>{if(!output)return;const result={...output,plannerNote:$('note').value,inputs:PANEL.hashes,code:PANEL.code};const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gymnote-web-'+run.scenario.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
start();
